export const cards = [
    { suit: "a", num: "2", url: "images/cards/a/2.png" },
    { suit: "a", num: "3", url: "images/cards/a/3.png" },
    { suit: "a", num: "4", url: "images/cards/a/4.png" },
    { suit: "a", num: "5", url: "images/cards/a/5.png" },
    { suit: "a", num: "6", url: "images/cards/a/6.png" },
    { suit: "a", num: "7", url: "images/cards/a/7.png" },
    { suit: "a", num: "8", url: "images/cards/a/8.png" },
    { suit: "a", num: "9", url: "images/cards/a/9.png" },
    { suit: "a", num: "10",url: "images/cards/a/10.png" },
    { suit: "a", num: "j", url: "images/cards/a/11.png" },
    { suit: "a", num: "q", url: "images/cards/a/12.png" },
    { suit: "a", num: "k", url: "images/cards/a/13.png" },
    { suit: "a", num: "a", url: "images/cards/a/14.png" },
    { suit: "b", num: "2", url: "images/cards/b/2.png" },
    { suit: "b", num: "3", url: "images/cards/b/3.png" },
    { suit: "b", num: "4", url: "images/cards/b/4.png" },
    { suit: "b", num: "5", url: "images/cards/b/5.png" },
    { suit: "b", num: "6", url: "images/cards/b/6.png" },
    { suit: "b", num: "7", url: "images/cards/b/7.png" },
    { suit: "b", num: "8", url: "images/cards/b/8.png" },
    { suit: "b", num: "9", url: "images/cards/b/9.png" },
    { suit: "b", num: "10",url: "images/cards/b/10.png" },
    { suit: "b", num: "j", url: "images/cards/b/11.png" },
    { suit: "b", num: "q", url: "images/cards/b/12.png" },
    { suit: "b", num: "k", url: "images/cards/b/13.png" },
    { suit: "b", num: "a", url: "images/cards/b/14.png" },
    { suit: "c", num: "2", url: "images/cards/b/2.png" },
    { suit: "c", num: "3", url: "images/cards/b/3.png" },
    { suit: "c", num: "4", url: "images/cards/b/4.png" },
    { suit: "c", num: "5", url: "images/cards/b/5.png" },
    { suit: "c", num: "6", url: "images/cards/b/6.png" },
    { suit: "c", num: "7", url: "images/cards/b/7.png" },
    { suit: "c", num: "8", url: "images/cards/b/8.png" },
    { suit: "c", num: "9", url: "images/cards/b/9.png" },
    { suit: "c", num: "10",url: "images/cards/b/10.png" },
    { suit: "c", num: "j", url: "images/cards/b/11.png" },
    { suit: "c", num: "q", url: "images/cards/b/12.png" },
    { suit: "c", num: "k", url: "images/cards/b/13.png" },
    { suit: "c", num: "a", url: "images/cards/b/14.png" },
    { suit: "d", num: "2", url: "images/cards/b/2.png" },
    { suit: "d", num: "3", url: "images/cards/b/3.png" },
    { suit: "d", num: "4", url: "images/cards/b/4.png" },
    { suit: "d", num: "5", url: "images/cards/b/5.png" },
    { suit: "d", num: "6", url: "images/cards/b/6.png" },
    { suit: "d", num: "7", url: "images/cards/b/7.png" },
    { suit: "d", num: "8", url: "images/cards/b/8.png" },
    { suit: "d", num: "9", url: "images/cards/b/9.png" },
    { suit: "d", num: "10",url: "images/cards/b/10.png" },
    { suit: "d", num: "j", url: "images/cards/b/11.png" },
    { suit: "d", num: "q", url: "images/cards/b/12.png" },
    { suit: "d", num: "k", url: "images/cards/b/13.png" },
    { suit: "d", num: "a", url: "images/cards/b/14.png" }
]